### ISSUE TITLE
How to increase the timeout in check_es_insert.py

### ISSUE THREAD

**Issue by Rumbles** [radu-gheorghe/check-es#11]
I am using this check on a number of servers, and most are fine, but one kept failing, I was getting the following error:

```There was an issue getting the status - and number of docs - from Elasticsearch. Check that ES is running and you have elasticsearch python module installed```

ES is running, I can run a healthcheck, but that server is a bit over loaded and can be a bit slow to respond. I did some digging and put a traceback in and found that the urllib lookup was timing out, some digging in the elasticsearch library found place to add the timeout, in my case, 30 seconds was necessary, I understand that might be a little high for most cases, but even if it is set to 10, t's useful to leave timeout in there, just so it's easy to find if someone needs to increase it later (and on't want to start digging through docs!)

**Comment by Rumbles** [comment]
Thanks!

**Comment by radu-gheorghe** [comment]
Thank YOU for contributing!
