### ISSUE TITLE
Issue using this with ES 2.1

### ISSUE THREAD

**Issue by Rumbles** [radu-gheorghe/check-es#9]
Hi,

Reading other issues I'm guessing you don't use this script much any more, but I wanted to use this to monitor some new es machines I have set up and I ran in to an immediate issue. I am running python 2.7.6, es 2.1.0 and pyes 0.99.6. My cluster is definitely running and pyes is installed, but running the script I get:

    ./check_es_insert.py -w 5000000 -c 10000000
    There was an issue getting the status - and number of docs - from Elasticsearch. Check that ES is running and you have pyes installed

Not sure if this would be an issue with pyes or the script, any ideas?

Thanks

**Comment by radu-gheorghe** [comment]
Hi @Rumbles. Thanks for reporting! Indeed, I haven't used this for a looong time now. I'll try to make it work again, though it will probably mean starting from scratch. I'll post here when I'm done.

**Comment by MiCRoPhoBIC** [comment]
I think the issue is that in the the ES 2.x the /_status is obsolete, but pyes still doesn't know this ;-)
https://www.elastic.co/guide/en/elasticsearch/reference/2.0/indices-status.html

**Comment by radu-gheorghe** [comment]
Maybe the latest pull request (https://github.com/radu-gheorghe/check-es/pull/10) fixed it by using the official Elasticsearch client? Sorry, I didn't have time to look into this but I'd gladly accept pull requests.

**Comment by Rumbles** [comment]
Thanks, I have raised myself a ticket to test this when I have some time, I'll update you with my results

**Comment by Rumbles** [comment]
I've tested this and this update has fixed most of my issues. Thanks!
